export const ADD_UNIT_TYPE_REQUEST = "ADD_UNIT_TYPE_REQUEST";
export const ADD_UNIT_TYPE_SUCCESS = "ADD_UNIT_TYPE_SUCCESS";
export const ADD_UNIT_TYPE_FAILURE = "ADD_UNIT_TYPE_FAILURE";

export const UPDATE_UNIT_TYPE_REQUEST = "UPDATE_UNIT_TYPE_REQUEST";
export const UPDATE_UNIT_TYPE_SUCCESS = "UPDATE_UNIT_TYPE_SUCCESS";
export const UPDATE_UNIT_TYPE_FAILURE = "UPDATE_UNIT_TYPE_FAILURE";

export const DELETE_UNIT_TYPE_REQUEST = "DELETE_UNIT_TYPE_REQUEST";
export const DELETE_UNIT_TYPE_SUCCESS = "DELETE_UNIT_TYPE_SUCCESS";
export const DELETE_UNIT_TYPE_FAILURE = "DELETE_UNIT_TYPE_FAILURE";

export const GET_UNIT_TYPES_REQUEST = "GET_UNIT_TYPES_REQUEST";
export const GET_UNIT_TYPES_SUCCESS = "GET_UNIT_TYPES_SUCCESS";
export const GET_UNIT_TYPES_FAILURE = "GET_UNIT_TYPES_FAILURE";

export const GET_UNIT_TYPE_REQUEST = "GET_UNIT_TYPE_REQUEST";
export const GET_UNIT_TYPE_SUCCESS = "GET_UNIT_TYPE_SUCCESS";
export const GET_UNIT_TYPE_FAILURE = "GET_UNIT_TYPE_FAILURE";
