export const SEARCH_PROPERTY_REQUEST = "SEARCH_PROPERTY_REQUEST";
export const SEARCH_PROPERTY_SUCCESS = "SEARCH_PROPERTY_SUCCESS";
export const SEARCH_PROPERTY_FAILURE = "SEARCH_PROPERTY_FAILURE";

export const ADD_PROPERTY_REQUEST = "ADD_PROPERTY_REQUEST";
export const ADD_PROPERTY_SUCCESS = "ADD_PROPERTY_SUCCESS";
export const ADD_PROPERTY_FAILURE = "ADD_PROPERTY_FAILURE";

export const UPDATE_PROPERTY_REQUEST = "UPDATE_PROPERTY_REQUEST";
export const UPDATE_PROPERTY_SUCCESS = "UPDATE_PROPERTY_SUCCESS";
export const UPDATE_PROPERTY_FAILURE = "UPDATE_PROPERTY_FAILURE";

export const DELETE_PROPERTY_REQUEST = "DELETE_PROPERTY";
export const DELETE_PROPERTY_SUCCESS = "DELETE_PROPERTY_SUCCESS";
export const DELETE_PROPERTY_FAILURE = "DELETE_PROPERTY_FAILURE";

export const GET_PROPERTIES_REQUEST = "GET_PROPERTIES_REQUEST";
export const GET_PROPERTIES_SUCCESS = "GET_PROPERTIES_SUCCESS";
export const GET_PROPERTIES_FAILURE = "GET_PROPERTIES_FAILURE";

export const GET_PROPERTIES_BY_USERID_REQUEST = "GET_PROPERTIES_BY_USERID_REQUEST";
export const GET_PROPERTIES_BY_USERID_SUCCESS = "GET_PROPERTIES_BY_USERID_SUCCESS";
export const GET_PROPERTIES_BY_USERID_FAILURE = "GET_PROPERTIES_BY_USERID_FAILURE";

export const GET_PROPERTY_REQUEST = "GET_PROPERTY_REQUEST";
export const GET_PROPERTY_SUCCESS = "GET_PROPERTY_SUCCESS";
export const GET_PROPERTY_FAILURE = "GET_PROPERTY_FAILURE";
