export const ADD_REPLY_REQUEST = "ADD_REPLY_REQUEST";
export const ADD_REPLY_SUCCESS = "ADD_REPLY_SUCCESS";
export const ADD_REPLY_FAILURE = "ADD_REPLY_FAILURE";

export const UPDATE_REPLY_REQUEST = "UPDATE_REPLY_REQUEST";
export const UPDATE_REPLY_SUCCESS = "UPDATE_REPLY_SUCCESS";
export const UPDATE_REPLY_FAILURE = "UPDATE_REPLY_FAILURE";

export const DELETE_REPLY_REQUEST = "DELETE_REPLY_REQUEST";
export const DELETE_REPLY_SUCCESS = "DELETE_REPLY_SUCCESS";
export const DELETE_REPLY_FAILURE = "DELETE_REPLY_FAILURE";

export const GET_REPLIES_REQUEST = "GET_REPLIES_REQUEST";
export const GET_REPLIES_SUCCESS = "GET_REPLIES_SUCCESS";
export const GET_REPLIES_FAILURE = "GET_REPLIES_FAILURE";

export const GET_REPLY_REQUEST = "GET_REPLY_REQUEST";
export const GET_REPLY_SUCCESS = "GET_REPLY_SUCCESS";
export const GET_REPLY_FAILURE = "GET_REPLY_FAILURE";
