export const DELETE_NOTIFICATION_REQUEST = "DELETE_NOTIFICATION_REQUEST";
export const DELETE_NOTIFICATION_SUCCESS = "DELETE_NOTIFICATION_SUCCESS";
export const DELETE_NOTIFICATION_FAILURE = "DELETE_NOTIFICATION_FAILURE";

export const GET_NOTIFICATIONS_BY_USERID_REQUEST = "GET_NOTIFICATIONS_BY_USERID_REQUEST";
export const GET_NOTIFICATIONS_BY_USERID_SUCCESS = "GET_NOTIFICATIONS_BY_USERID_SUCCESS";
export const GET_NOTIFICATIONS_BY_USERID_FAILURE = "GET_NOTIFICATIONS_BY_USERID_FAILURE";

export const UPDATE_NOTIFICATION_REQUEST = "UPDATE_NOTIFICATION_REQUEST";
export const UPDATE_NOTIFICATION_SUCCESS = "UPDATE_NOTIFICATION_SUCCESS";
export const UPDATE_NOTIFICATION_FAILURE = "UPDATE_NOTIFICATION_FAILURE";

export const UPDATE_NOTIFICATION_STATUS_REQUEST = "UPDATE_NOTIFICATION_STATUS_REQUEST";
export const UPDATE_NOTIFICATION_STATUS_SUCCESS = "UPDATE_NOTIFICATION_STATUS_SUCCESS";
export const UPDATE_NOTIFICATION_STATUS_FAILURE = "UPDATE_NOTIFICATION_STATUS_FAILURE";
