export const SEARCH_USER_PROPERTY_REQUEST = "SEARCH_USER_PROPERTY_REQUEST";
export const SEARCH_USER_PROPERTY_SUCCESS = "SEARCH_USER_PROPERTY_SUCCESS";
export const SEARCH_USER_PROPERTY_FAILURE = "SEARCH_USER_PROPERTY_FAILURE";

export const ADD_USER_PROPERTY_REQUEST = "ADD_USER_PROPERTY_REQUEST";
export const ADD_USER_PROPERTY_SUCCESS = "ADD_USER_PROPERTY_SUCCESS";
export const ADD_USER_PROPERTY_FAILURE = "ADD_USER_PROPERTY_FAILURE";

export const UPDATE_USER_PROPERTY_REQUEST = "UPDATE_USER_PROPERTY_REQUEST";
export const UPDATE_USER_PROPERTY_SUCCESS = "UPDATE_USER_PROPERTY_SUCCESS";
export const UPDATE_USER_PROPERTY_FAILURE = "UPDATE_USER_PROPERTY_FAILURE";

export const DELETE_USER_PROPERTY_REQUEST = "DELETE_USER_PROPERTY";
export const DELETE_USER_PROPERTY_SUCCESS = "DELETE_PROPERTY_SUCCESS";
export const DELETE_USER_PROPERTY_FAILURE = "DELETE_PROPERTY_FAILURE";

export const GET_USER_PROPERTIES_REQUEST = "ADD_USER_PROPERTIES_REQUEST";
export const GET_USER_PROPERTIES_SUCCESS = "GET_USER_PROPERTIES_SUCCESS";
export const GET_USER_PROPERTIES_FAILURE = "GET_USER_PROPERTIES_FAILURE";

export const GET_USER_PROPERTIES_BY_USERID_REQUEST = "ADD_USER_PROPERTIES_REQUEST";
export const GET_USER_PROPERTIES_BY_USERID_SUCCESS = "GET_USER_PROPERTIES_SUCCESS";
export const GET_USER_PROPERTIES_BY_USERID_FAILURE = "GET_USER_PROPERTIES_FAILURE";

export const GET_USER_PROPERTY_REQUEST = "GET_USER_PROPERTY_REQUEST";
export const GET_USER_PROPERTY_SUCCESS = "GET_USER_PROPERTY_SUCCESS";
export const GET_USER_PROPERTY_FAILURE = "GET_USER_PROPERTY_FAILURE";
