export const ADD_LIKE_REQUEST = "ADD_LIKE_REQUEST";
export const ADD_LIKE_SUCCESS = "ADD_LIKE_SUCCESS";
export const ADD_LIKE_FAILURE = "ADD_LIKE_FAILURE";

export const DELETE_LIKE_REQUEST = "DELETE_LIKE_REQUEST";
export const DELETE_LIKE_SUCCESS = "DELETE_LIKE_SUCCESS";
export const DELETE_LIKE_FAILURE = "DELETE_LIKE_FAILURE";

export const GET_LIKES_BY_USER_ID_REQUEST = "GET_LIKES_BY_USER_ID_REQUEST";
export const GET_LIKES_BY_USER_ID_SUCCESS = "GET_LIKES_BY_USER_ID_SUCCESS";
export const GET_LIKES_BY_USER_ID_FAILURE = "GET_LIKES_BY_USER_ID_FAILURE";

export const GET_LIKES_BY_COMMENT_ID_REQUEST = "GET_LIKES_BY_USER_ID_REQUEST";
export const GET_LIKES_BY_COMMENT_ID_SUCCESS = "GET_LIKES_BY_USER_ID_SUCCESS";
export const GET_LIKES_BY_COMMENT_ID_FAILURE = "GET_LIKES_BY_USER_ID_FAILURE";

export const UPDATE_LIKE_REQUEST = "UPDATE_LIKE_REQUEST";
export const UPDATE_LIKE_SUCCESS = "UPDATE_LIKE_SUCCESS";
export const UPDATE_LIKE_FAILURE = "UPDATE_LIKE_FAILURE";

// export const GET_LIKE_REQUEST = "GET_LIKE_REQUEST";
// export const GET_LIKE_SUCCESS = "GET_LIKE_SUCCESS";
// export const GET_LIKE_FAILURE = "GET_LIKE_FAILURE";
