export const ADD_DEVELOPER_REQUEST = "ADD_DEVELOPER_REQUEST";
export const ADD_DEVELOPER_SUCCESS = "ADD_DEVELOPER_SUCCESS";
export const ADD_DEVELOPER_FAILURE = "ADD_DEVELOPER_FAILURE";

export const UPDATE_DEVELOPER_REQUEST = "UPDATE_DEVELOPER_REQUEST";
export const UPDATE_DEVELOPER_SUCCESS = "UPDATE_DEVELOPER_SUCCESS";
export const UPDATE_DEVELOPER_FAILURE = "UPDATE_DEVELOPER_FAILURE";

export const DELETE_DEVELOPER_REQUEST = "DELETE_DEVELOPER_REQUEST";
export const DELETE_DEVELOPER_SUCCESS = "DELETE_DEVELOPER_SUCCESS";
export const DELETE_DEVELOPER_FAILURE = "DELETE_DEVELOPER_FAILURE";

export const GET_DEVELOPERS_REQUEST = "GET_DEVELOPERS_REQUEST";
export const GET_DEVELOPERS_SUCCESS = "GET_DEVELOPERS_SUCCESS";
export const GET_DEVELOPERS_FAILURE = "GET_DEVELOPERS_FAILURE";

export const GET_DEVELOPER_REQUEST = "GET_DEVELOPER_REQUEST";
export const GET_DEVELOPER_SUCCESS = "GET_DEVELOPER_SUCCESS";
export const GET_DEVELOPER_FAILURE = "GET_DEVELOPER_FAILURE";
