export const ADD_AMENITY_REQUEST = "ADD_AMENITY_REQUEST";
export const ADD_AMENITY_SUCCESS = "ADD_AMENITY_SUCCESS";
export const ADD_AMENITY_FAILURE = "ADD_AMENITY_FAILURE";

export const UPDATE_AMENITY_REQUEST = "UPDATE_AMENITY_REQUEST";
export const UPDATE_AMENITY_SUCCESS = "UPDATE_AMENITY_SUCCESS";
export const UPDATE_AMENITY_FAILURE = "UPDATE_AMENITY_FAILURE";

export const DELETE_AMENITY_REQUEST = "DELETE_AMENITY_REQUEST";
export const DELETE_AMENITY_SUCCESS = "DELETE_AMENITY_SUCCESS";
export const DELETE_AMENITY_FAILURE = "DELETE_AMENITY_FAILURE";

export const GET_AMENITIES_REQUEST = "GET_AMENITIES_REQUEST";
export const GET_AMENITIES_SUCCESS = "GET_AMENITIES_SUCCESS";
export const GET_AMENITIES_FAILURE = "GET_AMENITIES_FAILURE";

export const GET_AMENITY_REQUEST = "GET_AMENITY_REQUEST";
export const GET_AMENITY_SUCCESS = "GET_AMENITY_SUCCESS";
export const GET_AMENITY_FAILURE = "GET_AMENITY_FAILURE";
